use_frameworks!

platform :ios, '9.0'

target 'TheMovieDbAPIClient_Example' do
  pod 'TheMovieDbAPIClient', :path => '../'

  target 'TheMovieDbAPIClient_Tests' do
    inherit! :search_paths

    
  end
end
